export type WPPostType = {
  id: number;
  date: string;
  date_gmt: string;
  guid: { rendered: string };
  modified: string;
  modified_gmt: string;
  slug: string;
  status: "publish" | "future" | "draft" | "pending" | "private";
  type: "post";
  link: string;
  title: { rendered: string };
  content: { rendered: string; protected: boolean };
  excerpt: { rendered: string; protected: boolean };
  author: number;
  featured_media: number;
  comment_status: "open" | "closed";
  ping_status: "open" | "closed";
  sticky: boolean;
  template: string;
  format: string;
  meta: string;
  categories: number[];
  tags: number[];
  _embedded: {
    "wp:featuredmedia"?: { embeddable: boolean; href: string }[];
  };
  _links: {
    self: { href: string }[];
    collection: { href: string }[];
    about: { href: string }[];
    author: { embeddable: boolean; href: string }[];
    replies?: { embeddable: boolean; href: string }[];
    "version-history"?: { count: number; href: string }[];
    "predecessor-version"?: { id: number; href: string }[];
    "wp:attachment"?: { href: string }[];
    "wp:term"?: { taxonomy: string; embeddable: boolean; href: string }[];
    curies?: { name: string; href: string; templated: boolean }[];
  };
};
